<script setup lang="ts">
import { api } from '../../services/api'
import { relationshipTypes, type Asset, type AssetDetailModel, type AssetRelationship, type RelationshipFields, type RelationshipType } from '../../types/api'
const props = defineProps<{ asset: AssetDetailModel; assets: Asset[] }>()
const emit = defineEmits<{ refresh: [] }>()
const editing = ref<AssetRelationship | 'new' | null>(null)
const busy = ref(false)
const error = ref<string | null>(null)
const form = reactive({ sourceAssetId: '', targetAssetId: '', relationshipType: 'depends_on' as RelationshipType, notes: '' })
const assetOptions = computed(() => props.assets.map(row => ({ label: row.name, value: row.id })))
const typeOptions = relationshipTypes.map(value => ({ label: label(value), value }))
function label(value: string) { return value.replaceAll('_', ' ').replace(/^./, letter => letter.toUpperCase()) }
function name(id: string) { return props.assets.find(row => row.id === id)?.name || 'Unknown asset' }
function open(row: AssetRelationship | 'new') { editing.value = row; Object.assign(form, { sourceAssetId: row === 'new' ? props.asset.id : row.sourceAssetId, targetAssetId: row === 'new' ? props.assets.find(asset => asset.id !== props.asset.id)?.id || '' : row.targetAssetId, relationshipType: row === 'new' ? 'depends_on' : row.relationshipType, notes: row === 'new' ? '' : row.notes || '' }) }
async function save() { busy.value = true; error.value = null; try { const input: RelationshipFields = { sourceAssetId: form.sourceAssetId, targetAssetId: form.targetAssetId, relationshipType: form.relationshipType, notes: form.notes.trim() || null }; if (editing.value === 'new') await api.relationships.create(input); else if (editing.value) await api.relationships.update(editing.value.id, input); editing.value = null; emit('refresh') } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save relationship.' } finally { busy.value = false } }
async function remove(row: AssetRelationship) { if (!window.confirm('Delete this asset relationship?')) return; try { error.value = null; await api.relationships.delete(row.id); editing.value = null; emit('refresh') } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not delete relationship.' } }
</script>
<template>
  <section class="panel"><div class="section-heading"><h2 class="text-lg font-semibold">Relationships</h2><UButton size="sm" icon="i-lucide-plus" :disabled="assets.length < 2" @click="open('new')">Add relationship</UButton></div><div v-if="asset.relationships.length" class="table-scroll"><table class="data-table"><thead><tr><th>From</th><th>Relationship</th><th>To</th><th>Actions</th></tr></thead><tbody><tr v-for="row in asset.relationships" :key="row.id"><td><NuxtLink :to="`/assets/${row.sourceAssetId}`">{{ name(row.sourceAssetId) }}</NuxtLink><UBadge v-if="row.sourceAssetId === asset.id" size="xs" variant="subtle" class="ml-2">This asset</UBadge></td><td>{{ label(row.relationshipType) }}</td><td><NuxtLink :to="`/assets/${row.targetAssetId}`">{{ name(row.targetAssetId) }}</NuxtLink><UBadge v-if="row.targetAssetId === asset.id" size="xs" variant="subtle" class="ml-2">This asset</UBadge></td><td><div class="actions"><UButton size="xs" variant="outline" @click="open(row)">Edit</UButton><UButton size="xs" variant="outline" color="error" @click="remove(row)">Delete</UButton></div></td></tr></tbody></table></div><p v-else class="muted">No relationships recorded.</p><UAlert v-if="error" color="error" :title="error" class="mt-3" /></section>
  <section v-if="editing" class="panel"><h2 class="mb-4 text-lg font-semibold">{{ editing === 'new' ? 'Add relationship' : 'Edit relationship' }}</h2><form class="form-grid" @submit.prevent="save"><UFormField label="From asset" required><USelect v-model="form.sourceAssetId" :items="assetOptions" class="w-full" /></UFormField><UFormField label="Relationship"><USelect v-model="form.relationshipType" :items="typeOptions" class="w-full" /></UFormField><UFormField label="To asset" required><USelect v-model="form.targetAssetId" :items="assetOptions" class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="form.notes" class="w-full" /></UFormField><p v-if="form.sourceAssetId === form.targetAssetId" class="full text-red-300">Choose two different assets.</p><div class="form-actions full"><UButton type="button" variant="outline" color="neutral" @click="editing = null">Cancel</UButton><UButton type="submit" :loading="busy" :disabled="!form.sourceAssetId || !form.targetAssetId || form.sourceAssetId === form.targetAssetId">Save relationship</UButton></div></form></section>
</template>
