<script setup lang="ts">
import { api } from '../../services/api'
import { connectionTypes, interfaceTypes, portTypes, type AddressFields, type Asset, type AssetDetailModel, type ConnectionFields, type ConnectionType, type InterfaceFields, type IpAddress, type NetworkConnection, type NetworkInterface, type NetworkPort, type PortFields } from '../../types/api'
const props = defineProps<{ asset: AssetDetailModel; assets: Asset[] }>()
const emit = defineEmits<{ refresh: [] }>()
const allPorts = ref<NetworkPort[]>([])
const connections = ref<NetworkConnection[]>([])
const busy = ref(false)
const error = ref<string | null>(null)
const editingInterface = ref<NetworkInterface | 'new' | null>(null)
const editingAddress = ref<{ interfaceId: string; row: IpAddress | null } | null>(null)
const editingPort = ref<NetworkPort | 'new' | null>(null)
const connectingPort = ref<NetworkPort | null>(null)
const editingConnection = ref<NetworkConnection | null>(null)
const interfaceForm = reactive({ name: '', interfaceType: 'ethernet' as InterfaceFields['interfaceType'], macAddress: '', speedMbps: '', enabled: true, description: '', notes: '' })
const addressForm = reactive({ address: '', isPrimary: false, description: '' })
const portForm = reactive({ name: '', portType: 'rj45' as PortFields['portType'], portNumber: '', interfaceId: '', speedMbps: '', poeCapable: false, poeEnabled: false, enabled: true, description: '', notes: '' })
const connectionForm = reactive({ targetAssetId: '', targetPortId: '', connectionType: '' as ConnectionType | '', label: '', notes: '' })
const interfaceOptions = computed(() => [{ label: 'No interface', value: '' }, ...props.asset.interfaces.map(row => ({ label: row.name, value: row.id }))])
const targetAssets = computed(() => props.assets.filter(row => row.id !== props.asset.id && allPorts.value.some(port => port.assetId === row.id)).map(row => ({ label: row.name, value: row.id })))
const targetPorts = computed(() => allPorts.value.filter(row => row.assetId === connectionForm.targetAssetId && (!connectionFor(row.id) || connectionFor(row.id)?.id === editingConnection.value?.id)).map(row => ({ label: row.name, value: row.id })))
const typeOptions = (values: string[]) => values.map(value => ({ label: value.replaceAll('_', ' '), value }))
const speed = (value: number | null) => value === null ? '—' : value >= 1000 ? `${value / 1000} Gbps` : `${value} Mbps`
const assetName = (id: string) => props.assets.find(row => row.id === id)?.name || 'Unknown asset'
const portName = (id: string) => allPorts.value.find(row => row.id === id)?.name || 'Unknown port'
const connectionFor = (portId: string) => connections.value.find(row => row.portAId === portId || row.portBId === portId)
function peer(connection: NetworkConnection, portId: string) { const target = allPorts.value.find(row => row.id === (connection.portAId === portId ? connection.portBId : connection.portAId)); return target ? `${assetName(target.assetId)} · ${target.name}` : 'Unknown port' }
async function loadNetwork() { try { [allPorts.value, connections.value] = await Promise.all([api.network.ports.list(), api.network.connections.list()]) } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not load network data.' } }
onMounted(loadNetwork)
async function apply(operation: () => Promise<unknown>) { busy.value = true; error.value = null; try { await operation(); emit('refresh'); await loadNetwork(); editingInterface.value = null; editingAddress.value = null; editingPort.value = null; connectingPort.value = null; editingConnection.value = null } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Network change failed.' } finally { busy.value = false } }
function openInterface(row: NetworkInterface | 'new') { editingInterface.value = row; Object.assign(interfaceForm, { name: row === 'new' ? '' : row.name, interfaceType: row === 'new' ? 'ethernet' : row.interfaceType, macAddress: row === 'new' ? '' : row.macAddress || '', speedMbps: row === 'new' ? '' : String(row.speedMbps || ''), enabled: row === 'new' ? true : row.enabled, description: row === 'new' ? '' : row.description || '', notes: row === 'new' ? '' : row.notes || '' }) }
function saveInterface() { const input: InterfaceFields = { name: interfaceForm.name.trim(), interfaceType: interfaceForm.interfaceType, macAddress: interfaceForm.macAddress.trim() || null, speedMbps: interfaceForm.speedMbps ? Number(interfaceForm.speedMbps) : null, enabled: interfaceForm.enabled, description: interfaceForm.description.trim() || null, notes: interfaceForm.notes.trim() || null }; return apply(() => editingInterface.value === 'new' ? api.network.interfaces.create(props.asset.id, input) : api.network.interfaces.update((editingInterface.value as NetworkInterface).id, input)) }
function removeInterface(row: NetworkInterface) { if (window.confirm(`Delete network interface “${row.name}” and its IP addresses?`)) void apply(() => api.network.interfaces.delete(row.id)) }
function openAddress(interfaceId: string, row: IpAddress | null = null) { editingAddress.value = { interfaceId, row }; Object.assign(addressForm, { address: row?.address || '', isPrimary: row?.isPrimary || false, description: row?.description || '' }) }
function saveAddress() { if (!editingAddress.value) return; const input: AddressFields = { address: addressForm.address.trim(), isPrimary: addressForm.isPrimary, description: addressForm.description.trim() || null }; return apply(() => editingAddress.value!.row ? api.network.addresses.update(editingAddress.value!.row.id, input) : api.network.addresses.create(editingAddress.value!.interfaceId, input)) }
function removeAddress(row: IpAddress) { if (window.confirm(`Delete IP address ${row.address}?`)) void apply(() => api.network.addresses.delete(row.id)) }
function openPort(row: NetworkPort | 'new') { editingPort.value = row; Object.assign(portForm, { name: row === 'new' ? '' : row.name, portType: row === 'new' ? 'rj45' : row.portType, portNumber: row === 'new' ? '' : String(row.portNumber || ''), interfaceId: row === 'new' ? '' : row.interfaceId || '', speedMbps: row === 'new' ? '' : String(row.speedMbps || ''), poeCapable: row === 'new' ? false : row.poeCapable, poeEnabled: row === 'new' ? false : row.poeEnabled, enabled: row === 'new' ? true : row.enabled, description: row === 'new' ? '' : row.description || '', notes: row === 'new' ? '' : row.notes || '' }) }
function savePort() { const input: PortFields = { name: portForm.name.trim(), portType: portForm.portType, portNumber: portForm.portNumber ? Number(portForm.portNumber) : null, interfaceId: portForm.interfaceId || null, speedMbps: portForm.speedMbps ? Number(portForm.speedMbps) : null, poeCapable: portForm.poeCapable, poeEnabled: portForm.poeCapable && portForm.poeEnabled, enabled: portForm.enabled, description: portForm.description.trim() || null, notes: portForm.notes.trim() || null }; return apply(() => editingPort.value === 'new' ? api.network.ports.create(props.asset.id, input) : api.network.ports.update((editingPort.value as NetworkPort).id, input)) }
function removePort(row: NetworkPort) { if (window.confirm(`Delete network port “${row.name}”?`)) void apply(() => api.network.ports.delete(row.id)) }
function openConnection(row: NetworkPort) { connectingPort.value = row; editingConnection.value = null; Object.assign(connectionForm, { targetAssetId: targetAssets.value[0]?.value || '', targetPortId: '', connectionType: '', label: '', notes: '' }); connectionForm.targetPortId = targetPorts.value[0]?.value || '' }
function editConnection(row: NetworkConnection, port: NetworkPort) { const peerId = row.portAId === port.id ? row.portBId : row.portAId; const target = allPorts.value.find(item => item.id === peerId); if (!target) return; connectingPort.value = port; editingConnection.value = row; Object.assign(connectionForm, { targetAssetId: target.assetId, targetPortId: target.id, connectionType: row.connectionType || '', label: row.label || '', notes: row.notes || '' }) }
function saveConnection() { if (!connectingPort.value) return; const input: ConnectionFields = { portAId: connectingPort.value.id, portBId: connectionForm.targetPortId, connectionType: connectionForm.connectionType || null, label: connectionForm.label.trim() || null, notes: connectionForm.notes.trim() || null }; return apply(() => editingConnection.value ? api.network.connections.update(editingConnection.value.id, input) : api.network.connections.create(input)) }
function disconnect(row: NetworkConnection) { if (window.confirm('Disconnect these ports?')) void apply(() => api.network.connections.delete(row.id)) }
</script>
<template>
  <h2 class="inventory-heading">Network</h2>
  <UAlert v-if="error" color="error" :title="error" class="mb-4" />
  <section class="panel"><div class="section-heading"><h3 class="text-lg font-semibold">Interfaces and IP addresses</h3><UButton size="sm" icon="i-lucide-plus" @click="openInterface('new')">Add interface</UButton></div>
    <div v-if="asset.interfaces.length" class="table-scroll"><table class="data-table"><thead><tr><th>Name</th><th>Type</th><th>MAC</th><th>Speed</th><th>Enabled</th><th>IP addresses</th><th>Actions</th></tr></thead><tbody><tr v-for="row in asset.interfaces" :key="row.id"><td>{{ row.name }}</td><td>{{ row.interfaceType }}</td><td>{{ row.macAddress || '—' }}</td><td>{{ speed(row.speedMbps) }}</td><td>{{ row.enabled ? 'Yes' : 'No' }}</td><td><div v-for="address in row.ipAddresses" :key="address.id" class="inline"><span>{{ address.address }}{{ address.isPrimary ? ' · Primary' : '' }}</span><UButton size="xs" variant="ghost" @click="openAddress(row.id, address)">Edit</UButton><UButton size="xs" color="error" variant="ghost" @click="removeAddress(address)">Delete</UButton></div><UButton size="xs" variant="outline" @click="openAddress(row.id)">Add IP</UButton></td><td><div class="actions"><UButton size="xs" variant="outline" @click="openInterface(row)">Edit</UButton><UButton size="xs" color="error" variant="outline" @click="removeInterface(row)">Delete</UButton></div></td></tr></tbody></table></div><p v-else class="muted">No interfaces recorded.</p>
  </section>
  <section v-if="editingInterface" class="panel"><h3 class="mb-4 text-lg font-semibold">{{ editingInterface === 'new' ? 'Add interface' : 'Edit interface' }}</h3><form class="form-grid" @submit.prevent="saveInterface"><UFormField label="Name" required><UInput v-model="interfaceForm.name" required class="w-full" /></UFormField><UFormField label="Type"><USelect v-model="interfaceForm.interfaceType" :items="typeOptions(interfaceTypes)" class="w-full" /></UFormField><UFormField label="MAC address"><UInput v-model="interfaceForm.macAddress" placeholder="aa:bb:cc:dd:ee:ff" class="w-full" /></UFormField><UFormField label="Speed (Mbps)"><UInput v-model="interfaceForm.speedMbps" type="number" min="1" class="w-full" /></UFormField><UFormField label="Description"><UInput v-model="interfaceForm.description" class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="interfaceForm.notes" class="w-full" /></UFormField><UCheckbox v-model="interfaceForm.enabled" label="Enabled" /><div class="form-actions full"><UButton type="button" variant="outline" @click="editingInterface = null">Cancel</UButton><UButton type="submit" :loading="busy">Save interface</UButton></div></form></section>
  <section v-if="editingAddress" class="panel"><h3 class="mb-4 text-lg font-semibold">{{ editingAddress.row ? 'Edit IP address' : 'Add IP address' }}</h3><form class="form-grid" @submit.prevent="saveAddress"><UFormField label="IPv4 or IPv6 address" required><UInput v-model="addressForm.address" required placeholder="192.0.2.10/24" class="w-full" /></UFormField><UFormField label="Description"><UInput v-model="addressForm.description" class="w-full" /></UFormField><UCheckbox v-model="addressForm.isPrimary" label="Primary address" /><div class="form-actions full"><UButton type="button" variant="outline" @click="editingAddress = null">Cancel</UButton><UButton type="submit" :loading="busy">Save IP</UButton></div></form></section>
  <section class="panel"><div class="section-heading"><h3 class="text-lg font-semibold">Physical ports and connections</h3><UButton size="sm" icon="i-lucide-plus" @click="openPort('new')">Add port</UButton></div><div v-if="asset.ports.length" class="table-scroll"><table class="data-table"><thead><tr><th>Port</th><th>Type</th><th>Speed</th><th>PoE</th><th>Enabled</th><th>Connected to</th><th>Actions</th></tr></thead><tbody><tr v-for="row in asset.ports" :key="row.id"><td>{{ row.name }}</td><td>{{ row.portType.replaceAll('_', ' ') }}</td><td>{{ speed(row.speedMbps) }}</td><td>{{ row.poeCapable ? row.poeEnabled ? 'On' : 'Capable' : '—' }}</td><td>{{ row.enabled ? 'Yes' : 'No' }}</td><td><template v-if="connectionFor(row.id)"><span>{{ peer(connectionFor(row.id)!, row.id) }}</span><span v-if="connectionFor(row.id)?.label"> · {{ connectionFor(row.id)?.label }}</span></template><span v-else>—</span></td><td><div class="actions"><UButton size="xs" variant="outline" @click="openPort(row)">Edit</UButton><UButton v-if="connectionFor(row.id)" size="xs" variant="outline" @click="editConnection(connectionFor(row.id)!, row)">Edit link</UButton><UButton v-if="connectionFor(row.id)" size="xs" color="error" variant="outline" @click="disconnect(connectionFor(row.id)!)">Disconnect</UButton><UButton v-else size="xs" variant="outline" @click="openConnection(row)">Connect</UButton><UButton size="xs" color="error" variant="outline" @click="removePort(row)">Delete</UButton></div></td></tr></tbody></table></div><p v-else class="muted">No physical ports recorded.</p></section>
  <section v-if="editingPort" class="panel"><h3 class="mb-4 text-lg font-semibold">{{ editingPort === 'new' ? 'Add port' : 'Edit port' }}</h3><form class="form-grid" @submit.prevent="savePort"><UFormField label="Port name" required><UInput v-model="portForm.name" required class="w-full" /></UFormField><UFormField label="Type"><USelect v-model="portForm.portType" :items="typeOptions(portTypes)" class="w-full" /></UFormField><UFormField label="Port number"><UInput v-model="portForm.portNumber" type="number" min="1" class="w-full" /></UFormField><UFormField label="Speed (Mbps)"><UInput v-model="portForm.speedMbps" type="number" min="1" class="w-full" /></UFormField><UFormField label="Interface"><USelect v-model="portForm.interfaceId" :items="interfaceOptions" class="w-full" /></UFormField><UFormField label="Description"><UInput v-model="portForm.description" class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="portForm.notes" class="w-full" /></UFormField><div class="inline"><UCheckbox v-model="portForm.enabled" label="Enabled" /><UCheckbox v-model="portForm.poeCapable" label="PoE capable" /><UCheckbox v-model="portForm.poeEnabled" label="PoE enabled" :disabled="!portForm.poeCapable" /></div><div class="form-actions full"><UButton type="button" variant="outline" @click="editingPort = null">Cancel</UButton><UButton type="submit" :loading="busy">Save port</UButton></div></form></section>
  <section v-if="connectingPort" class="panel"><h3 class="mb-4 text-lg font-semibold">{{ editingConnection ? 'Edit connection' : `Connect ${connectingPort.name}` }}</h3><form class="form-grid" @submit.prevent="saveConnection"><UFormField label="Target asset"><USelect v-model="connectionForm.targetAssetId" :items="targetAssets" class="w-full" @update:model-value="connectionForm.targetPortId = ''" /></UFormField><UFormField label="Target port"><USelect v-model="connectionForm.targetPortId" :items="targetPorts" class="w-full" /></UFormField><UFormField label="Connection type"><USelect v-model="connectionForm.connectionType" :items="[{ label: 'Unspecified', value: '' }, ...typeOptions(connectionTypes)]" class="w-full" /></UFormField><UFormField label="Label"><UInput v-model="connectionForm.label" class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="connectionForm.notes" class="w-full" /></UFormField><div class="form-actions full"><UButton type="button" variant="outline" @click="connectingPort = null">Cancel</UButton><UButton type="submit" :loading="busy" :disabled="!connectionForm.targetPortId">Save connection</UButton></div></form></section>
</template>
