import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { confirmDelete, Empty, ErrorNotice, Field, Loading, optional } from '../components/ui'
import { api } from '../services/api'
import type { Asset, Component, Location, LocationFields, Rack } from '../types/api'

export default function Locations() {
  const [locations, setLocations] = useState<Location[]>([])
  const [assets, setAssets] = useState<Asset[]>([])
  const [components, setComponents] = useState<Component[]>([])
  const [racks, setRacks] = useState<Rack[]>([])
  const [editing, setEditing] = useState<Location | 'new' | null>(null)
  const [name, setName] = useState('')
  const [parentId, setParentId] = useState('')
  const [description, setDescription] = useState('')
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { let active = true; void Promise.all([api.locations.list(), api.assets.list(), api.components.list(), api.racks.list()]).then(([places, machines, parts, shelves]) => { if (active) { setLocations(places); setAssets(machines); setComponents(parts); setRacks(shelves) } }).catch(cause => { if (active) setError(cause.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  const tree = useMemo(() => { const result: { location: Location; depth: number }[] = []; const visited = new Set<string>(); function walk(parent: string | null, depth: number) { for (const location of locations.filter(row => row.parentId === parent)) { if (visited.has(location.id)) continue; visited.add(location.id); result.push({ location, depth }); walk(location.id, depth + 1) } } walk(null, 0); for (const location of locations) if (!visited.has(location.id)) { visited.add(location.id); result.push({ location, depth: 0 }); walk(location.id, 1) } return result }, [locations])
  function open(location: Location | 'new', suggestedParent = '') { setEditing(location); setName(location === 'new' ? '' : location.name); setParentId(location === 'new' ? suggestedParent : location.parentId || ''); setDescription(location === 'new' ? '' : location.description || ''); setError(null) }
  async function save(event: FormEvent) { event.preventDefault(); setError(null); setBusy(true); try { const input: LocationFields = { name: name.trim(), parentId: parentId || null, description: optional(description) }; const row = editing === 'new' ? await api.locations.create(input) : await api.locations.update((editing as Location).id, input); setLocations(rows => editing === 'new' ? [...rows, row] : rows.map(item => item.id === row.id ? row : item)); setEditing(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save location.') } finally { setBusy(false) } }
  async function remove(location: Location) { if (!confirmDelete(location.name)) return; setError(null); try { await api.locations.delete(location.id); setLocations(rows => rows.filter(row => row.id !== location.id)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete location.') } }
  return <><div className="page-heading"><div><p className="eyebrow">Infrastructure</p><h1>Locations</h1><p className="muted">Places that hold assets and spare hardware.</p></div><button onClick={() => open('new')}>+ New location</button></div><ErrorNotice error={error} />
    {editing && <section className="panel"><h2>{editing === 'new' ? 'Create location' : `Edit ${editing.name}`}</h2><form className="form-grid" onSubmit={e => void save(e)}><Field label="Name"><input required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Parent location"><select value={parentId} onChange={e => setParentId(e.target.value)}><option value="">Root location</option>{locations.filter(row => editing === 'new' || row.id !== editing.id).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><div className="full"><Field label="Description"><textarea rows={3} value={description} onChange={e => setDescription(e.target.value)} /></Field></div><div className="form-actions"><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button><button disabled={busy} type="submit">{busy ? 'Saving…' : 'Save location'}</button></div></form></section>}
    {loading ? <Loading /> : <section className="panel table-panel">{tree.length ? <div className="table-scroll"><table><thead><tr><th>Location</th><th>Description</th><th>Assets</th><th>Racks</th><th>Components</th><th>Actions</th></tr></thead><tbody>{tree.map(({ location, depth }) => { const assignedAssets = assets.filter(asset => asset.locationId === location.id); const assignedComponents = components.filter(component => component.locationId === location.id); const assignedRacks = racks.filter(rack => rack.locationId === location.id); return <tr key={location.id}><td><span className="location-indent" style={{ paddingLeft: `${Math.min(depth, 6) * 22}px` }}>{depth > 0 && '↳ '}{location.name}</span></td><td>{location.description || '—'}</td><td>{assignedAssets.length ? assignedAssets.map(asset => <div key={asset.id}><Link to={`/assets/${asset.id}`}>{asset.name}</Link></div>) : '—'}</td><td>{assignedRacks.length ? assignedRacks.map(rack => <div key={rack.id}><Link to={`/racks/${rack.id}`}>{rack.name}</Link></div>) : '—'}</td><td>{assignedComponents.length ? assignedComponents.map(component => component.name).join(', ') : '—'}</td><td><div className="inline"><button className="secondary small" onClick={() => open('new', location.id)}>Add child</button><button className="secondary small" onClick={() => open(location)}>Edit</button><button className="danger-outline small" onClick={() => void remove(location)}>Delete</button></div></td></tr> })}</tbody></table></div> : <Empty>No locations yet. Create a place such as Home or Server Room.</Empty>}</section>}
  </>
}
