import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Empty, ErrorNotice, Field, optional } from './ui'
import { api } from '../services/api'
import { connectionTypes, portTypes, type Asset, type AssetDetailModel, type ConnectionType, type NetworkConnection, type NetworkPort, type PortFields } from '../types/api'

const speed = (value: number | null) => value == null ? '—' : value >= 1000 ? `${value / 1000} Gbps` : `${value} Mbps`
export default function AssetPorts({ asset, assets, allPorts, connections, onRefresh }: { asset: AssetDetailModel; assets: Asset[]; allPorts: NetworkPort[]; connections: NetworkConnection[]; onRefresh: () => Promise<void> }) {
  const [editing, setEditing] = useState<NetworkPort | 'new' | null>(null)
  const [name, setName] = useState('')
  const [portNumber, setPortNumber] = useState('')
  const [portType, setPortType] = useState<PortFields['portType']>('rj45')
  const [interfaceId, setInterfaceId] = useState('')
  const [speedMbps, setSpeedMbps] = useState('')
  const [poeCapable, setPoeCapable] = useState(false)
  const [poeEnabled, setPoeEnabled] = useState(false)
  const [enabled, setEnabled] = useState(true)
  const [description, setDescription] = useState('')
  const [notes, setNotes] = useState('')
  const [connectPort, setConnectPort] = useState<NetworkPort | null>(null)
  const [editingConnection, setEditingConnection] = useState<NetworkConnection | null>(null)
  const [peerAssetId, setPeerAssetId] = useState('')
  const [peerPortId, setPeerPortId] = useState('')
  const [connectionType, setConnectionType] = useState<ConnectionType | ''>('')
  const [label, setLabel] = useState('')
  const [connectionNotes, setConnectionNotes] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  function open(row: NetworkPort | 'new') { setEditing(row); setName(row === 'new' ? '' : row.name); setPortNumber(row === 'new' || row.portNumber == null ? '' : String(row.portNumber)); setPortType(row === 'new' ? 'rj45' : row.portType); setInterfaceId(row === 'new' ? '' : row.interfaceId || ''); setSpeedMbps(row === 'new' || row.speedMbps == null ? '' : String(row.speedMbps)); setPoeCapable(row === 'new' ? false : row.poeCapable); setPoeEnabled(row === 'new' ? false : row.poeEnabled); setEnabled(row === 'new' ? true : row.enabled); setDescription(row === 'new' ? '' : row.description || ''); setNotes(row === 'new' ? '' : row.notes || '') }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const input: PortFields = { name: name.trim(), portNumber: portNumber ? Number(portNumber) : null, portType, interfaceId: interfaceId || null, speedMbps: speedMbps ? Number(speedMbps) : null, poeCapable, poeEnabled, enabled, description: optional(description), notes: optional(notes) }; if (editing === 'new') await api.network.ports.create(asset.id, input); else await api.network.ports.update((editing as NetworkPort).id, input); await onRefresh(); setEditing(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save port.') } finally { setBusy(false) } }
  async function remove(row: NetworkPort) { if (!window.confirm(`Delete port “${row.name}”? Its connection may also be removed.`)) return; setError(null); try { await api.network.ports.delete(row.id); await onRefresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete port.') } }
  function openConnection(port: NetworkPort, connection: NetworkConnection | null) { const peerId = connection ? connection.portAId === port.id ? connection.portBId : connection.portAId : ''; const peer = allPorts.find(row => row.id === peerId); const available = allPorts.filter(row => row.id !== port.id && !connections.some(item => item.id !== connection?.id && (item.portAId === row.id || item.portBId === row.id))); const nextAssetId = peer?.assetId || available[0]?.assetId || ''; setConnectPort(port); setEditingConnection(connection); setPeerAssetId(nextAssetId); setPeerPortId(peerId || available.find(row => row.assetId === nextAssetId)?.id || ''); setConnectionType(connection?.connectionType || ''); setLabel(connection?.label || ''); setConnectionNotes(connection?.notes || '') }
  async function saveConnection(event: FormEvent) { event.preventDefault(); if (!connectPort || !peerPortId) return; setBusy(true); setError(null); try { const input = { portAId: connectPort.id, portBId: peerPortId, connectionType: connectionType || null, label: optional(label), notes: optional(connectionNotes) }; if (editingConnection) await api.network.connections.update(editingConnection.id, input); else await api.network.connections.create(input); await onRefresh(); setConnectPort(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save connection.') } finally { setBusy(false) } }
  async function disconnect(connection: NetworkConnection) { if (!window.confirm('Disconnect these ports?')) return; setError(null); try { await api.network.connections.delete(connection.id); await onRefresh(); setConnectPort(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not disconnect ports.') } }
  return <section className="panel"><div className="section-heading"><h2>Physical ports and connections</h2><button className="small" onClick={() => open('new')}>+ Add port</button></div><ErrorNotice error={error} />
    {asset.ports.length ? <div className="table-scroll"><table><thead><tr><th>Port</th><th>Type</th><th>Interface</th><th>Speed</th><th>PoE</th><th>Enabled</th><th>Connected to</th><th>Actions</th></tr></thead><tbody>{asset.ports.map(port => { const connection = connections.find(row => row.portAId === port.id || row.portBId === port.id); const peer = connection && allPorts.find(row => row.id === (connection.portAId === port.id ? connection.portBId : connection.portAId)); const peerAsset = peer && assets.find(row => row.id === peer.assetId); return <tr key={port.id}><td>{port.name}</td><td>{port.portType.replaceAll('_', ' ')}</td><td>{asset.interfaces.find(row => row.id === port.interfaceId)?.name || '—'}</td><td>{speed(port.speedMbps)}</td><td>{port.poeEnabled ? 'On' : port.poeCapable ? 'Capable' : '—'}</td><td>{port.enabled ? 'Yes' : 'No'}</td><td>{peer ? <>{peerAsset ? <Link to={`/assets/${peerAsset.id}`}>{peerAsset.name}</Link> : 'Unknown asset'} / {peer.name}{connection?.label && <div className="cell-subtitle">{connection.label}</div>}</> : '—'}</td><td><div className="inline"><button className="secondary small" onClick={() => open(port)}>Edit</button><button className="secondary small" onClick={() => openConnection(port, connection || null)}>{connection ? 'Connection' : 'Connect'}</button><button className="danger-outline small" onClick={() => void remove(port)}>Delete</button></div></td></tr> })}</tbody></table></div> : <Empty>No physical ports.</Empty>}
    {editing && <form className="form-grid subpanel" onSubmit={e => void save(e)}><h3 className="full">{editing === 'new' ? 'Add port' : `Edit ${editing.name}`}</h3><Field label="Name"><input required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Port number"><input type="number" min="1" value={portNumber} onChange={e => setPortNumber(e.target.value)} /></Field><Field label="Type"><select value={portType} onChange={e => setPortType(e.target.value as PortFields['portType'])}>{portTypes.map(type => <option key={type} value={type}>{type.replaceAll('_', ' ')}</option>)}</select></Field><Field label="Interface"><select value={interfaceId} onChange={e => setInterfaceId(e.target.value)}><option value="">No interface</option>{asset.interfaces.map(iface => <option key={iface.id} value={iface.id}>{iface.name}</option>)}</select></Field><Field label="Speed (Mbps)"><input type="number" min="1" value={speedMbps} onChange={e => setSpeedMbps(e.target.value)} /></Field><Field label="Description"><input value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="Notes"><input value={notes} onChange={e => setNotes(e.target.value)} /></Field><Field label="PoE capable"><input type="checkbox" checked={poeCapable} onChange={e => { setPoeCapable(e.target.checked); if (!e.target.checked) setPoeEnabled(false) }} /></Field><Field label="PoE enabled"><input type="checkbox" disabled={!poeCapable} checked={poeEnabled} onChange={e => setPoeEnabled(e.target.checked)} /></Field><Field label="Enabled"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /></Field><div className="form-actions"><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button><button disabled={busy}>Save port</button></div></form>}
    {connectPort && <form className="form-grid subpanel" onSubmit={e => void saveConnection(e)}><h3 className="full">{editingConnection ? 'Edit connection' : `Connect ${connectPort.name}`}</h3><Field label="Peer asset"><select required value={peerAssetId} onChange={e => { setPeerAssetId(e.target.value); setPeerPortId(allPorts.find(row => row.assetId === e.target.value && row.id !== connectPort.id && !connections.some(item => item.id !== editingConnection?.id && (item.portAId === row.id || item.portBId === row.id)))?.id || '') }}>{assets.filter(row => allPorts.some(item => item.assetId === row.id && item.id !== connectPort.id && !connections.some(connection => connection.id !== editingConnection?.id && (connection.portAId === item.id || connection.portBId === item.id)))).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Peer port"><select required value={peerPortId} onChange={e => setPeerPortId(e.target.value)}>{allPorts.filter(row => row.assetId === peerAssetId && row.id !== connectPort.id && !connections.some(item => item.id !== editingConnection?.id && (item.portAId === row.id || item.portBId === row.id))).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Connection type"><select value={connectionType} onChange={e => setConnectionType(e.target.value as ConnectionType | '')}><option value="">Unspecified</option>{connectionTypes.map(type => <option key={type} value={type}>{type}</option>)}</select></Field><Field label="Label"><input value={label} onChange={e => setLabel(e.target.value)} /></Field><div className="full"><Field label="Notes"><input value={connectionNotes} onChange={e => setConnectionNotes(e.target.value)} /></Field></div><div className="form-actions">{editingConnection && <button type="button" className="danger-outline" onClick={() => void disconnect(editingConnection)}>Disconnect</button>}<button className="secondary" type="button" onClick={() => setConnectPort(null)}>Cancel</button><button disabled={busy || !peerPortId}>Save connection</button></div></form>}
  </section>
}
