import { useState, type FormEvent } from 'react'
import { Empty, ErrorNotice, Field, optional } from './ui'
import { api } from '../services/api'
import { interfaceTypes, type AssetDetailModel, type InterfaceFields, type IpAddress, type NetworkInterface } from '../types/api'

function speed(value: number | null) { return value == null ? '—' : value >= 1000 ? `${value / 1000} Gbps` : `${value} Mbps` }
export default function AssetInterfaces({ asset, onRefresh }: { asset: AssetDetailModel; onRefresh: () => Promise<void> }) {
  const [editing, setEditing] = useState<NetworkInterface | 'new' | null>(null)
  const [name, setName] = useState('')
  const [interfaceType, setInterfaceType] = useState<InterfaceFields['interfaceType']>('ethernet')
  const [macAddress, setMacAddress] = useState('')
  const [speedMbps, setSpeedMbps] = useState('')
  const [enabled, setEnabled] = useState(true)
  const [description, setDescription] = useState('')
  const [notes, setNotes] = useState('')
  const [addressInterface, setAddressInterface] = useState<string | null>(null)
  const [editingAddress, setEditingAddress] = useState<IpAddress | 'new' | null>(null)
  const [address, setAddress] = useState('')
  const [primary, setPrimary] = useState(false)
  const [addressDescription, setAddressDescription] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  function open(row: NetworkInterface | 'new') { setEditing(row); setName(row === 'new' ? '' : row.name); setInterfaceType(row === 'new' ? 'ethernet' : row.interfaceType); setMacAddress(row === 'new' ? '' : row.macAddress || ''); setSpeedMbps(row === 'new' ? '' : String(row.speedMbps || '')); setEnabled(row === 'new' ? true : row.enabled); setDescription(row === 'new' ? '' : row.description || ''); setNotes(row === 'new' ? '' : row.notes || '') }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const input: InterfaceFields = { name: name.trim(), interfaceType, macAddress: optional(macAddress), speedMbps: speedMbps ? Number(speedMbps) : null, enabled, description: optional(description), notes: optional(notes) }; if (editing === 'new') await api.network.interfaces.create(asset.id, input); else await api.network.interfaces.update((editing as NetworkInterface).id, input); await onRefresh(); setEditing(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save interface.') } finally { setBusy(false) } }
  async function remove(row: NetworkInterface) { if (!window.confirm(`Delete interface “${row.name}”? Its IP addresses may also be removed.`)) return; setError(null); try { await api.network.interfaces.delete(row.id); await onRefresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete interface.') } }
  function openAddress(interfaceId: string, row: IpAddress | 'new') { setAddressInterface(interfaceId); setEditingAddress(row); setAddress(row === 'new' ? '' : row.address); setPrimary(row === 'new' ? false : row.isPrimary); setAddressDescription(row === 'new' ? '' : row.description || '') }
  async function saveAddress(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const input = { address: address.trim(), isPrimary: primary, description: optional(addressDescription) }; if (editingAddress === 'new') await api.network.addresses.create(addressInterface!, input); else await api.network.addresses.update((editingAddress as IpAddress).id, input); await onRefresh(); setEditingAddress(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save IP address.') } finally { setBusy(false) } }
  async function removeAddress(row: IpAddress) { if (!window.confirm(`Delete ${row.address}?`)) return; setError(null); try { await api.network.addresses.delete(row.id); await onRefresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete IP address.') } }
  return <section className="panel"><div className="section-heading"><h2>Interfaces and IP addresses</h2><button className="small" onClick={() => open('new')}>+ Add interface</button></div><ErrorNotice error={error} />
    {asset.interfaces.length ? asset.interfaces.map(iface => <div className="subpanel" key={iface.id}><div className="section-heading"><div><strong>{iface.name}</strong> · {iface.interfaceType} · {speed(iface.speedMbps)} · {iface.enabled ? 'Enabled' : 'Disabled'}<p className="muted">MAC {iface.macAddress || '—'}{iface.description && ` · ${iface.description}`}</p></div><div className="inline"><button className="secondary small" onClick={() => open(iface)}>Edit</button><button className="danger-outline small" onClick={() => void remove(iface)}>Delete</button></div></div><div className="section-heading"><h3>IP addresses</h3><button className="secondary small" onClick={() => openAddress(iface.id, 'new')}>+ Add IP</button></div>{iface.ipAddresses.length ? <div className="table-scroll"><table><thead><tr><th>Address</th><th>Primary</th><th>Description</th><th>Actions</th></tr></thead><tbody>{iface.ipAddresses.map(ip => <tr key={ip.id}><td>{ip.address}</td><td>{ip.isPrimary ? 'Primary' : '—'}</td><td>{ip.description || '—'}</td><td><div className="inline"><button className="secondary small" onClick={() => openAddress(iface.id, ip)}>Edit</button><button className="danger-outline small" onClick={() => void removeAddress(ip)}>Delete</button></div></td></tr>)}</tbody></table></div> : <Empty>No IP addresses.</Empty>}</div>) : <Empty>No network interfaces.</Empty>}
    {editing && <form className="form-grid subpanel" onSubmit={e => void save(e)}><h3 className="full">{editing === 'new' ? 'Add interface' : `Edit ${editing.name}`}</h3><Field label="Name"><input required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Type"><select value={interfaceType} onChange={e => setInterfaceType(e.target.value as InterfaceFields['interfaceType'])}>{interfaceTypes.map(type => <option key={type} value={type}>{type}</option>)}</select></Field><Field label="MAC address"><input value={macAddress} onChange={e => setMacAddress(e.target.value)} placeholder="aa:bb:cc:dd:ee:ff" /></Field><Field label="Speed (Mbps)"><input type="number" min="1" value={speedMbps} onChange={e => setSpeedMbps(e.target.value)} /></Field><Field label="Description"><input value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="Notes"><input value={notes} onChange={e => setNotes(e.target.value)} /></Field><Field label="Enabled"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /></Field><div className="form-actions"><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button><button disabled={busy}>Save interface</button></div></form>}
    {editingAddress && <form className="form-grid subpanel" onSubmit={e => void saveAddress(e)}><h3 className="full">{editingAddress === 'new' ? 'Add IP address' : 'Edit IP address'}</h3><Field label="IPv4 or IPv6 address"><input required value={address} onChange={e => setAddress(e.target.value)} placeholder="192.0.2.10/24 or 2001:db8::10/64" /></Field><Field label="Description"><input value={addressDescription} onChange={e => setAddressDescription(e.target.value)} /></Field><Field label="Primary"><input type="checkbox" checked={primary} onChange={e => setPrimary(e.target.checked)} /></Field><div className="form-actions"><button className="secondary" type="button" onClick={() => setEditingAddress(null)}>Cancel</button><button disabled={busy}>Save address</button></div></form>}
  </section>
}
