<script setup lang="ts">
import { api } from '../../../services/api'
import type { Asset, Location, PlacementFields, RackDetail, RackFields, RackOrientation, RackPlacement } from '../../../types/api'
const route = useRoute()
const id = computed(() => String(route.params.id))
const rack = ref<RackDetail | null>(null)
const assets = ref<Asset[]>([])
const locations = ref<Location[]>([])
const view = ref<RackOrientation>('front')
const editingRack = ref(false)
const editingPlacement = ref<RackPlacement | 'new' | null>(null)
const rackForm = reactive({ name: '', totalUnits: 42, startingUnit: 1, locationId: '', description: '', notes: '' })
const placementForm = reactive({ assetId: '', startUnit: 1, heightUnits: 1, orientation: 'front' as RackOrientation, notes: '' })
const loading = ref(true)
const busy = ref(false)
const error = ref<string | null>(null)
const locationOptions = computed(() => [{ label: 'No location', value: '' }, ...locations.value.map(place => ({ label: place.name, value: place.id }))])
const assetOptions = computed(() => assets.value.map(asset => ({ label: asset.name, value: asset.id })))
const units = computed(() => rack.value ? Array.from({ length: rack.value.totalUnits }, (_, index) => rack.value!.startingUnit + rack.value!.totalUnits - 1 - index) : [])
onMounted(async () => { try { [rack.value, assets.value, locations.value] = await Promise.all([api.racks.get(id.value), api.assets.list(), api.locations.list()]) } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not load rack.' } finally { loading.value = false } })
async function refresh() { rack.value = await api.racks.get(id.value) }
function openRack() { if (!rack.value) return; Object.assign(rackForm, { name: rack.value.name, totalUnits: rack.value.totalUnits, startingUnit: rack.value.startingUnit, locationId: rack.value.locationId || '', description: rack.value.description || '', notes: rack.value.notes || '' }); editingRack.value = true }
function openPlacement(row: RackPlacement | 'new') { if (!rack.value) return; editingPlacement.value = row; Object.assign(placementForm, { assetId: row === 'new' ? assets.value[0]?.id || '' : row.assetId, startUnit: row === 'new' ? rack.value.startingUnit : row.startUnit, heightUnits: row === 'new' ? 1 : row.heightUnits, orientation: row === 'new' ? view.value : row.orientation, notes: row === 'new' ? '' : row.notes || '' }) }
function placementAt(unit: number) { return rack.value?.placements.find(row => row.orientation === view.value && row.startUnit <= unit && unit < row.startUnit + row.heightUnits) }
async function saveRack() { busy.value = true; error.value = null; try { const input: RackFields = { name: rackForm.name.trim(), totalUnits: Number(rackForm.totalUnits), startingUnit: Number(rackForm.startingUnit), locationId: rackForm.locationId || null, description: rackForm.description.trim() || null, notes: rackForm.notes.trim() || null }; await api.racks.update(id.value, input); await refresh(); editingRack.value = false } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not update rack.' } finally { busy.value = false } }
async function savePlacement() { busy.value = true; error.value = null; try { const input: PlacementFields = { assetId: placementForm.assetId, startUnit: Number(placementForm.startUnit), heightUnits: Number(placementForm.heightUnits), orientation: placementForm.orientation, notes: placementForm.notes.trim() || null }; if (editingPlacement.value === 'new') await api.racks.placements.create(id.value, input); else await api.racks.placements.update(id.value, (editingPlacement.value as RackPlacement).id, input); await refresh(); editingPlacement.value = null; view.value = input.orientation || 'front' } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save placement.' } finally { busy.value = false } }
async function removePlacement(row: RackPlacement) { if (!window.confirm(`Remove ${row.asset.name} from this rack?`)) return; error.value = null; try { await api.racks.placements.delete(id.value, row.id); await refresh(); editingPlacement.value = null } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not remove placement.' } }
async function removeRack() { if (!rack.value || !window.confirm(`Permanently delete “${rack.value.name}”?`)) return; error.value = null; try { await api.racks.delete(id.value); await navigateTo('/racks') } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not delete rack.' } }
</script>

<template>
  <NuxtLink to="/racks" class="block mb-5 text-cyan-300">← Racks</NuxtLink>
  <UCard v-if="loading"><div role="status">Loading rack…</div></UCard>
  <template v-else-if="rack"><div class="page-heading"><div><p class="eyebrow">Rack</p><h1>{{ rack.name }}</h1><p class="muted">{{ rack.totalUnits }}U · {{ locations.find(row => row.id === rack?.locationId)?.name || 'No location' }}</p></div><div class="actions"><UButton variant="outline" @click="openRack">Edit rack</UButton><UButton color="error" variant="outline" @click="removeRack">Delete rack</UButton></div></div><UAlert v-if="error" color="error" :title="error" class="mb-4" />
    <section v-if="editingRack" class="panel"><h2 class="mb-4 text-lg font-semibold">Edit rack</h2><form class="form-grid" @submit.prevent="saveRack"><UFormField label="Name" required><UInput v-model="rackForm.name" required class="w-full" /></UFormField><UFormField label="Location"><USelect v-model="rackForm.locationId" :items="locationOptions" class="w-full" /></UFormField><UFormField label="Total U"><UInput v-model="rackForm.totalUnits" type="number" min="1" max="100" class="w-full" /></UFormField><UFormField label="Starting U"><UInput v-model="rackForm.startingUnit" type="number" min="1" class="w-full" /></UFormField><UFormField label="Description"><UInput v-model="rackForm.description" class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="rackForm.notes" class="w-full" /></UFormField><div class="form-actions full"><UButton type="button" variant="outline" color="neutral" @click="editingRack = false">Cancel</UButton><UButton type="submit" :loading="busy">Save rack</UButton></div></form></section>
    <section class="panel"><div class="section-heading"><h2 class="text-lg font-semibold">Rack layout</h2><UButton icon="i-lucide-plus" :disabled="!assets.length" @click="openPlacement('new')">Place asset</UButton></div><div class="actions my-4" role="group" aria-label="Rack orientation"><UButton :variant="view === 'front' ? 'solid' : 'outline'" :aria-pressed="view === 'front'" @click="view = 'front'">Front</UButton><UButton :variant="view === 'rear' ? 'solid' : 'outline'" :aria-pressed="view === 'rear'" @click="view = 'rear'">Rear</UButton></div><div class="rack-layout" :aria-label="`${rack.name} ${view} layout`"><div v-for="unit in units" :key="unit" class="rack-unit"><span class="rack-number">{{ unit }}U</span><div :class="placementAt(unit) ? 'rack-occupied' : 'rack-empty'"><template v-if="placementAt(unit)"><template v-if="unit === placementAt(unit)!.startUnit + placementAt(unit)!.heightUnits - 1"><NuxtLink :to="`/assets/${placementAt(unit)!.assetId}`">{{ placementAt(unit)!.asset.name }}</NuxtLink><DeviceFaceplate :asset-id="placementAt(unit)!.assetId" :name="placementAt(unit)!.asset.name" :manufacturer="assets.find(asset => asset.id === placementAt(unit)!.assetId)?.manufacturer" :model="assets.find(asset => asset.id === placementAt(unit)!.assetId)?.model" :side="view" compact /><span class="muted text-xs">{{ placementAt(unit)!.heightUnits }}U</span><UButton size="xs" variant="outline" @click="openPlacement(placementAt(unit)!)">Edit</UButton></template><span v-else aria-hidden="true">│</span></template><span v-else>Empty</span></div></div></div><p class="muted mt-3">Front and rear placements are shown separately. Multi-unit assets fill every occupied U.</p></section>
    <section v-if="editingPlacement" class="panel"><h2 class="mb-4 text-lg font-semibold">{{ editingPlacement === 'new' ? 'Place asset' : 'Edit placement' }}</h2><form class="form-grid" @submit.prevent="savePlacement"><UFormField label="Asset" required><USelect v-model="placementForm.assetId" :items="assetOptions" class="w-full" /></UFormField><UFormField label="Orientation"><USelect v-model="placementForm.orientation" :items="[{ label: 'Front', value: 'front' }, { label: 'Rear', value: 'rear' }]" class="w-full" /></UFormField><UFormField label="Starting U"><UInput v-model="placementForm.startUnit" type="number" :min="rack.startingUnit" :max="rack.startingUnit + rack.totalUnits - 1" required class="w-full" /></UFormField><UFormField label="Height U"><UInput v-model="placementForm.heightUnits" type="number" min="1" required class="w-full" /></UFormField><UFormField label="Notes" class="full"><UInput v-model="placementForm.notes" class="w-full" /></UFormField><div class="form-actions full"><UButton v-if="editingPlacement !== 'new'" type="button" color="error" variant="outline" @click="removePlacement(editingPlacement!)">Remove placement</UButton><UButton type="button" variant="outline" color="neutral" @click="editingPlacement = null">Cancel</UButton><UButton type="submit" :loading="busy" :disabled="!placementForm.assetId">Save placement</UButton></div></form></section>
  </template>
  <UAlert v-else color="error" :title="error || 'Rack not found.'" />
</template>
